apiVersion: v1
kind: Pod
metadata:
 name: webapp
 namespace: myapp
 labels:
   app: web
   env: dev
spec:
  containers:
  - name: webcon
    # image: srinivasaprasad28/medplus:v1
    image: srinivasaprasad28/dev1:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      name: apache
      protocol: TCP
    resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
 name: websvc
 namespace: myapp
spec:
 type: LoadBalancer
 ports:
 - name: apache
   port: 80
   targetPort: 80
   protocol: TCP
 selector:
   app: web
   env: dev
